In [6]:
import numpy as np
import glob, tqdm
import sys, dill
import datetime

In [3]:
np.zeros((4, 5)).max(-1)

array([0., 0., 0., 0.])

In [5]:
def sort_fn(filename):
    date_string = filename[-14:-4]
    datetime_object = datetime.datetime.strptime(date_string, "%Y-%m-%d")
    return datetime_object
def save_object(obj, filename):
    dill.dump(obj, file=open(filename, "wb"))

data_dir = "../data"
splits = ["CAM5", "SPCAM5"]
# splits = ["CAM5"]
x_max = 0
y_max = 0
x_min = 0
y_min = 0

for split in splits:
    x_paths = sorted(glob.glob(f"{data_dir}/{split}/inputs*"), key=sort_fn)[:365]
    y_paths = sorted(glob.glob(f"{data_dir}/{split}/outputs*"), key=sort_fn)[:365]

    for i, (x_f, y_f) in tqdm.tqdm(enumerate(zip(x_paths, y_paths)), total=len(y_paths)):
        x = np.load(x_f, mmap_mode='r')
        y = np.load(y_f, mmap_mode='r')
        x_max = np.maximum(x_max, np.max(x, 0))
        y_max = np.maximum(y_max, np.max(y, 0))
        x_min = np.minimum(x_min, np.min(x, 0))
        y_min = np.minimum(y_min, np.min(y, 0))

    np.save(f"../scalers/{split}_x_max.npy", x_max)
    np.save(f"../scalers/{split}_y_max.npy", y_max)
    np.save(f"../scalers/{split}_x_min.npy", x_min)
    np.save(f"../scalers/{split}_y_min.npy", y_min)


100%|██████████| 365/365 [00:47<00:00,  7.71it/s]


In [7]:
l1_x_max = np.load("../scalers/CAM5_x_max.npy")
l1_x_min = np.load("../scalers/CAM5_x_min.npy")
l1_y_max = np.load("../scalers/CAM5_y_max.npy")
l1_y_min = np.load("../scalers/CAM5_y_min.npy")
l2_x_max = np.load("../scalers/SPCAM5_x_max.npy")
l2_x_min = np.load("../scalers/SPCAM5_x_min.npy")
l2_y_max = np.load("../scalers/SPCAM5_y_max.npy")
l2_y_min = np.load("../scalers/SPCAM5_y_min.npy")

In [20]:
import sys
sys.path.append('../src/SFNP/')
from lib.utils import MinMaxScaler, StandardScaler

In [21]:
l1_x_scaler_minmax = dill.load(open('../scalers/x_CAM5_minmax_scaler.dill', 'rb'))

In [24]:
l1_x_scaler_minmax.max == l1_x_max

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

array([2.77426758e+02, 2.69584564e+02, 2.64400452e+02, 2.60852417e+02,
       2.54367340e+02, 2.50192810e+02, 2.46686691e+02, 2.45020264e+02,
       2.42068619e+02, 2.39250793e+02, 2.39442535e+02, 2.40342361e+02,
       2.42080078e+02, 2.45708694e+02, 2.45818939e+02, 2.54548615e+02,
       2.63270081e+02, 2.71797302e+02, 2.76961792e+02, 2.83947479e+02,
       2.92566071e+02, 3.02001953e+02, 3.10036774e+02, 3.15763550e+02,
       3.19691193e+02, 3.21801392e+02, 1.88973854e-06, 1.87160617e-06,
       1.88490878e-06, 1.92133439e-06, 1.92560560e-06, 2.12575014e-06,
       3.33829917e-06, 1.38219097e-04, 7.71799008e-04, 1.10595103e-03,
       1.47442066e-03, 1.71812484e-03, 2.26741494e-03, 2.36729882e-03,
       2.72311387e-03, 3.53110977e-03, 4.64665657e-03, 6.79808948e-03,
       9.25564580e-03, 1.22102397e-02, 1.36217745e-02, 1.62387900e-02,
       1.91608332e-02, 2.21411064e-02, 2.34411731e-02, 2.71806400e-02,
       0.00000000e+00, 0.00000000e+00, 1.27769805e-38, 2.64542116e-27,
      